# {PROJECT}/.github/workflows/main.yaml
# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  build:
    env: 
      BASE_URL: /vue3-ecom/
      VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
      VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
      VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
      VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
      VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
      VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      # Pick your own package manager and build script
      - run: npm install
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: page
          path: build
          if-no-files-found: error
  
  unitTest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js "20"
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - name: Execute Unit tests
        run: |
          npm ci
          npm run test:unit 
    
  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: unitTest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github_pages environment
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: page
          path: .
      - uses: actions/configure-pages@v1
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@main
